using System;
using System.Diagnostics;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using nifly;

namespace ImmersiveEquipmentDisplay
{
    public class ScriptLess
    {
        static Lazy<Settings> _settings = null!;
        static public Settings settings => _settings.Value;

        private static IPatcherState<ISkyrimMod, ISkyrimModGetter>? patcherState;
        public static IPatcherState<ISkyrimMod, ISkyrimModGetter> PatcherState
        {
            get => patcherState!;
        }

        public static Task<int> Main(string[] args)
        {
            return SynthesisPipeline.Instance.SetTypicalOpen(GameRelease.SkyrimSE, "ImmersiveEquipmentMeshGen.esp")
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
                .Run(args);
        }

        // save options set to simplify binary comparison of output vs Edit Script output
        // optimization and sorting should be kept off by default
        public static readonly nifly.NifSaveOptions saveOptions = new NifSaveOptions()
        {
            optimize = false,
            sortBlocks = false
        };

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            patcherState = state;

            settings.diagnostics.logger.WriteLine("Game release: {0}", state.GameRelease.ToString());

            // Validate Settings, abort if invalid
            var settingsErrors = _settings.Value.GetConfigErrors();
            if (settingsErrors.Count > 0)
            {
                settings.diagnostics.logger.WriteLine("Settings Errors: {0}", settingsErrors.Count);
                foreach (var error in settingsErrors)
                {
                    settings.diagnostics.logger.WriteLine(error);
                }
                throw new ArgumentException("Bad Settings: ImmersiveEquipment Patcher cannot run. Check diagnostic output and fix problems.");
            }

            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();

            // Analyze records in scope for models and textures
            MeshHandler meshHandler = new MeshHandler(settings);
            meshHandler.Analyze();
            long analysisTime = stopWatch.ElapsedMilliseconds;

            // Transform meshes, including any records with alternate textures
            meshHandler.TransformMeshes(state);
            long meshTime = stopWatch.ElapsedMilliseconds - analysisTime;

            settings.diagnostics.logger.WriteLine("Records analysis: {0} ms", analysisTime);
            settings.diagnostics.logger.WriteLine("Mesh transformation: {0} ms", meshTime);
        }
    }
}
